# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exos', '0002_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='auteur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
